scss_files: '_assets/css/**/*.scss'
linters:
  NestingDepth:
    enabled: false
  QualifyingElement:
    enabled: false
  StringQuotes:
    enabled: false
  LeadingZero:
    enabled: false
  NameFormat:
    enabled: false
