sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
branches:
  only:
  - master
env:
  - JEKYLL_ENV=production
script:
  - ./build.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: teamt5.org
  local_dir: .build/
  on:
    branch: master
