baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

host: 0.0.0.0

# Set default value

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      locale: en
  -
    scope:
      path: "_positions"
      type: "positions"
    values:
      layout: "position"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Collections

collections:
  positions:
    output: true
    permalink: /:collection/:title

plugins:
  - jekyll-coffeescript
  - jekyll-assets
  - normalize-scss
  - font-awesome-sass
  - jekyll-paginate-v2
  - jekyll-admin

# i18n

locales:
  - en
  - zh

# jekyll-assets

assets:
  caching:
    type: memory


# jekyll-paginate-v2

pagination:
  permalink: '/page/:num/'
  enabled: true
  debug: true
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page
