#!/bin/bash

DIR=$( cd "$( dirname "$0" )" && pwd )
PATH=$DIR/sbin:$PATH
TARGET=${DIR}/config

cd "${TARGET}"
erb "./allowed.conf.erb" > "./allowed.conf"
erb "./locations.conf.erb" > "./locations.conf"
cd sites
for site in ./*.conf.erb
do
	erb "$site" > "${site%.*}"
done

cd "${DIR}"
exec $*
